const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const { execFile } = require("node:child_process");
const { promisify } = require("node:util");
const test = require("node:test");
const { createInitFixture } = require("./init-test-helpers");

const execFileAsync = promisify(execFile);
const cliEntry = path.join(__dirname, "..", "dist", "index.js");
const ansiPattern = /\u001B\[[0-9;]*m/gu;

test("Build uses the default adapter and prints the bootstrap prompt after a successful build", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  const { stderr, stdout } = await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);
  const normalizedStdout = stdout.replace(ansiPattern, "");

  assert.equal(stderr, "");
  assert.match(
    normalizedStdout,
    /┌─+┐/u,
  );
  assert.match(
    normalizedStdout,
    /│ Build complete\. Generated canonical context file \.aie-os[\\/]build[\\/]effective-context\.json and AGENTS\.md\. │/u,
  );
  assert.match(
    normalizedStdout,
    /└─+┘/u,
  );
  assert.match(normalizedStdout, /Bootstrap prompt/u);
  assert.match(
    normalizedStdout,
    /Use this first prompt in the next agent session to make sure the agent reloads and follows the instructions from the context you just built\./u,
  );
  assert.match(
    normalizedStdout,
    /Read `AGENTS\.md` at the repo root and treat it as the authoritative instruction set/u,
  );
  assert.match(
    normalizedStdout,
    /reload `AGENTS\.md` from disk before continuing instead of relying on memory\./u,
  );

  await fs.access(path.join(fixture.projectPath, "AGENTS.md"));
  await fs.access(path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"));
});

test("Build writes the file named by --output-file and not the default name", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  const { stdout } = await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
    "--output-file",
    "CLAUDE.md",
  ]);
  const normalizedStdout = stdout.replace(ansiPattern, "");

  assert.match(normalizedStdout, /Generated canonical context file .* and CLAUDE\.md\./u);
  assert.match(normalizedStdout, /Read `CLAUDE\.md` at the repo root/u);

  await fs.access(path.join(fixture.projectPath, "CLAUDE.md"));
  await assert.rejects(fs.access(path.join(fixture.projectPath, "AGENTS.md")));
});

test("Build overwrites its own generated file without requiring a flag", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  const buildArguments = [cliEntry, "build", "--project-path", fixture.projectPath];

  await execFileAsync(process.execPath, buildArguments);
  const firstContents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  await execFileAsync(process.execPath, buildArguments);
  const secondContents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.equal(secondContents, firstContents);
});

test("Build refuses to overwrite a file it did not generate and explains the way forward", async () => {
  const fixture = await createInitFixture();
  const outputFilePath = path.join(fixture.projectPath, "AGENTS.md");

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  await fs.writeFile(outputFilePath, "# Hand written instructions\n");

  await assert.rejects(
    execFileAsync(process.execPath, [cliEntry, "build", "--project-path", fixture.projectPath]),
    (error) => {
      assert.equal(error.code, 1);
      assert.match(
        error.stderr,
        /Refusing to overwrite AGENTS\.md: it was not generated by AIE OS\./u,
      );
      assert.match(
        error.stderr,
        /Pass --force-overwrite to replace it, or choose another name with --output-file\./u,
      );
      return true;
    },
  );

  assert.equal(await fs.readFile(outputFilePath, "utf8"), "# Hand written instructions\n");
});

test("Build replaces a file it did not generate when --force-overwrite is passed", async () => {
  const fixture = await createInitFixture();
  const outputFilePath = path.join(fixture.projectPath, "AGENTS.md");

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  await fs.writeFile(outputFilePath, "# Hand written instructions\n");

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
    "--force-overwrite",
  ]);

  const contents = await fs.readFile(outputFilePath, "utf8");

  assert.match(contents, /This file is generated by AIE OS\. Do not edit directly\./u);
});

test("Build keeps Conditional Rules in effective context but merges them into Coding Rules in AGENTS output", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--languages",
    "typescript",
    "--application-type",
    "cli",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const effectiveContext = JSON.parse(
    await fs.readFile(
      path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"),
      "utf8",
    ),
  );
  const agentsContents = await fs.readFile(
    path.join(fixture.projectPath, "AGENTS.md"),
    "utf8",
  );

  assert.equal(
    effectiveContext.sections.some((section) =>
      section.sectionLabel === "Conditional Rules" &&
      section.content.includes("Conditional CLI TypeScript rule.")),
    true,
  );
  assert.doesNotMatch(agentsContents, /^## Conditional Rules$/mu);
  assert.match(agentsContents, /^## Coding Rules$/mu);
  assert.match(agentsContents, /Conditional CLI TypeScript rule\./u);
});

test("Build loads selected application-type and framework Markdown files", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--application-type",
    "cli",
    "--frameworks",
    "react",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const effectiveContext = JSON.parse(
    await fs.readFile(
      path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"),
      "utf8",
    ),
  );

  assert.equal(
    effectiveContext.sections.some((section) =>
      section.sectionLabel === "Application Type: cli" &&
      section.content.includes("Keep CLI commands composable.")),
    true,
  );
  assert.equal(
    effectiveContext.sections.some((section) =>
      section.sectionLabel === "Framework: react" &&
      section.content.includes("Keep React components focused.")),
    true,
  );
});

test("Build succeeds when the knowledge-base layer is disabled", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    "",
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const effectiveContext = JSON.parse(
    await fs.readFile(
      path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"),
      "utf8",
    ),
  );

  assert.equal(effectiveContext.persona.source, path.join(fixture.agentPath, "persona", "software-developer.md"));
  assert.equal(
    effectiveContext.sections.some((section) =>
      section.layer === "Engineering Principles" ||
      section.layer === "Shared Coding Rules" ||
      section.layer === "Language Rules" ||
      section.layer === "Application-Type Rules" ||
      section.layer === "Framework Rules" ||
      section.layer === "Conditional Coding Rules"),
    false,
  );
});

test("Build renders one section heading per layer and a sub-heading for every file after the first", async () => {
  const fixture = await createInitFixture();
  const principlesPath = path.join(
    fixture.knowledgeBasePath,
    "engineering-principles",
    "universal",
  );

  await fs.writeFile(
    path.join(principlesPath, "1-engineering-principles.md"),
    "- Ship small and fast.\n",
  );
  await fs.writeFile(
    path.join(principlesPath, "2-architecture-principles.md"),
    "- Keep boundaries clean.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "coding-rules", "universal", "coding-rules.md"),
    "- Keep modules focused.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(
    agents,
    /## Engineering Principles\n\n- Ship small and fast\.\n\n### Architecture Principles\n\n- Keep boundaries clean\./u,
  );
  assert.equal(agents.includes("### Engineering Principles"), false);
  assert.match(agents, /## Coding Rules\n\n- Keep modules focused\./u);
  assert.equal(agents.includes("### Coding Rules\n\n- Keep modules focused."), false);
});
