const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const { execFile } = require("node:child_process");
const { promisify } = require("node:util");
const test = require("node:test");
const { createInitFixture } = require("./init-test-helpers");

const execFileAsync = promisify(execFile);
const cliEntry = path.join(__dirname, "..", "dist", "index.js");
const ansiPattern = /\u001B\[[0-9;]*m/gu;

test("Build uses the default adapter and prints the bootstrap prompt after a successful build", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);

  const { stderr, stdout } = await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);
  const normalizedStdout = stdout.replace(ansiPattern, "");

  assert.equal(stderr, "");
  assert.match(
    normalizedStdout,
    /┌─+┐/u,
  );
  assert.match(
    normalizedStdout,
    /│ Build complete\. Generated canonical context file \.aie-os[\\/]build[\\/]effective-context\.json and AGENTS\.md\. │/u,
  );
  assert.match(
    normalizedStdout,
    /└─+┘/u,
  );
  assert.match(normalizedStdout, /Bootstrap prompt/u);
  assert.match(
    normalizedStdout,
    /Use this first prompt in the next agent session to make sure the agent reloads and follows the instructions from the context you just built\./u,
  );
  assert.match(
    normalizedStdout,
    /Read `AGENTS\.md` at the repo root and treat it as the authoritative instruction set/u,
  );
  assert.match(
    normalizedStdout,
    /reload `AGENTS\.md` from disk before continuing instead of relying on memory\./u,
  );

  await fs.access(path.join(fixture.projectPath, "AGENTS.md"));
  await fs.access(path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"));
});

test("Build overwrites its own generated file without requiring a flag", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);

  const buildArguments = [cliEntry, "build", "--project-path", fixture.projectPath];

  await execFileAsync(process.execPath, buildArguments);
  const firstContents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  await execFileAsync(process.execPath, buildArguments);
  const secondContents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.equal(secondContents, firstContents);
});

test("Build refuses to overwrite a file it did not generate and explains the way forward", async () => {
  const fixture = await createInitFixture();
  const outputFilePath = path.join(fixture.projectPath, "AGENTS.md");

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);

  await fs.writeFile(outputFilePath, "# Hand written instructions\n");

  await assert.rejects(
    execFileAsync(process.execPath, [cliEntry, "build", "--project-path", fixture.projectPath]),
    (error) => {
      assert.equal(error.code, 1);
      assert.match(
        error.stderr,
        /Refusing to overwrite AGENTS\.md: it was not generated by AIE OS\./u,
      );
      assert.match(
        error.stderr,
        /Pass --force-overwrite to replace it\./u,
      );
      return true;
    },
  );

  assert.equal(await fs.readFile(outputFilePath, "utf8"), "# Hand written instructions\n");
});

test("Build replaces a file it did not generate when --force-overwrite is passed", async () => {
  const fixture = await createInitFixture();
  const outputFilePath = path.join(fixture.projectPath, "AGENTS.md");

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);

  await fs.writeFile(outputFilePath, "# Hand written instructions\n");

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
    "--force-overwrite",
  ]);

  const contents = await fs.readFile(outputFilePath, "utf8");

  assert.match(contents, /This file is generated by AIE OS\. Do not edit directly\./u);
});

test("Build keeps Conditional Rules in effective context but merges them into Coding Rules in AGENTS output", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
    "--languages",
    "typescript",
    "--application-type",
    "cli",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const effectiveContext = JSON.parse(
    await fs.readFile(
      path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"),
      "utf8",
    ),
  );
  const agentsContents = await fs.readFile(
    path.join(fixture.projectPath, "AGENTS.md"),
    "utf8",
  );

  assert.equal(
    effectiveContext.sections.some((section) =>
      section.sectionLabel === "Conditional Rules" &&
      section.content.includes("Conditional CLI TypeScript rule.")),
    true,
  );
  assert.doesNotMatch(agentsContents, /^## Conditional Rules$/mu);
  assert.match(agentsContents, /^## Coding Rules$/mu);
  assert.match(agentsContents, /Conditional CLI TypeScript rule\./u);
});

test("Build loads selected application-type and framework Markdown files", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
    "--application-type",
    "cli",
    "--frameworks",
    "react",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const effectiveContext = JSON.parse(
    await fs.readFile(
      path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"),
      "utf8",
    ),
  );

  assert.equal(
    effectiveContext.sections.some((section) =>
      section.sectionLabel === "Application Type: cli" &&
      section.content.includes("Keep CLI commands composable.")),
    true,
  );
  assert.equal(
    effectiveContext.sections.some((section) =>
      section.sectionLabel === "Framework: react" &&
      section.content.includes("Keep React components focused.")),
    true,
  );
});

test("Build succeeds when the knowledge-base layer is disabled", async () => {
  const fixture = await createInitFixture();

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    "",
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const effectiveContext = JSON.parse(
    await fs.readFile(
      path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"),
      "utf8",
    ),
  );

  assert.equal(effectiveContext.persona.source, path.join(fixture.agentPath, "persona", "software-developer.md"));
  assert.equal(
    effectiveContext.sections.some((section) =>
      section.layer === "Shared Coding Rules" ||
      section.layer === "Language Rules" ||
      section.layer === "Application-Type Rules" ||
      section.layer === "Framework Rules" ||
      section.layer === "Conditional Coding Rules"),
    false,
  );
});

test("Build renders one section heading per layer and a sub-heading for every file after the first", async () => {
  const fixture = await createInitFixture();
  const principlesPath = path.join(
    fixture.knowledgeBasePath,
    "general-principles",
    "universal",
  );

  await fs.writeFile(
    path.join(principlesPath, "1-engineering-principles.md"),
    "- Ship small and fast.\n",
  );
  await fs.writeFile(
    path.join(path.dirname(principlesPath), "architecture", "2-architecture-principles.md"),
    "- Keep boundaries clean.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "coding-rules", "universal", "coding-rules.md"),
    "- Keep modules focused.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
    "--languages",
    "typescript",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(
    agents,
    /## Engineering Principles\n\n- Ship small and fast\.\n\n### Architecture Principles\n\n- Keep boundaries clean\./u,
  );
  assert.equal(agents.includes("### Engineering Principles"), false);
  assert.match(agents, /## Coding Rules\n\n- Keep modules focused\./u);
  assert.equal(agents.includes("### Coding Rules\n\n- Keep modules focused."), false);
});

test("Build loads only the principles from the knowledge base when no language, application type, or framework is selected", async () => {
  const fixture = await createInitFixture();

  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "universal", "principles.md"),
    "- Ship small and fast.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "coding-rules", "universal", "coding-rules.md"),
    "- Keep modules focused.\n",
  );
  await fs.writeFile(
    path.join(fixture.agentPath, "universal", "universal.md"),
    "- Agent rule that always applies.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(agents, /## Engineering Principles\n\n- Ship small and fast\./u);
  assert.equal(agents.includes("Keep modules focused."), false);
  assert.equal(agents.includes("## Coding Rules"), false);

  assert.match(agents, /## Persona/u);
  assert.match(agents, /- Agent rule that always applies\./u);
});

test("Build gives a persona that includes architecture principles both principle sets and no coding rules without a technical selection", async () => {
  const fixture = await createInitFixture();

  await fs.writeFile(
    path.join(fixture.agentPath, "persona", "solutions-architect.md"),
    "---\nincludes: [architecture-principles]\n---\n\nYou are the solutions-architect.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "universal", "1-engineering-principles.md"),
    "- Ship small and fast.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "architecture", "2-architecture-principles.md"),
    "- Keep boundaries clean.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "coding-rules", "universal", "coding-rules.md"),
    "- Keep modules focused.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "solutions-architect",
    "--tool",
    "codex",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(agents, /You are the solutions-architect\./u);
  assert.equal(agents.includes("includes:"), false);
  assert.match(agents, /- Ship small and fast\./u);
  assert.equal(agents.includes("Keep boundaries clean."), true);
  assert.equal(agents.includes("Keep modules focused."), false);
});

test("Build gives a persona without the architecture include only the engineering principles without a technical selection", async () => {
  const fixture = await createInitFixture();

  await fs.writeFile(
    path.join(fixture.agentPath, "persona", "solutions-engineer.md"),
    "You are the solutions-engineer.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "universal", "1-engineering-principles.md"),
    "- Ship small and fast.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "architecture", "2-architecture-principles.md"),
    "- Keep boundaries clean.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "coding-rules", "universal", "coding-rules.md"),
    "- Keep modules focused.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "solutions-engineer",
    "--tool",
    "codex",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(agents, /You are the solutions-engineer\./u);
  assert.equal(agents.includes("includes:"), false);
  assert.match(agents, /- Ship small and fast\./u);
  assert.equal(agents.includes("Keep boundaries clean."), false);
  assert.equal(agents.includes("Keep modules focused."), false);
});

test("Build adds architecture principles and coding rules to any persona when a technical selection exists", async () => {
  const fixture = await createInitFixture();

  await fs.writeFile(
    path.join(fixture.agentPath, "persona", "solutions-engineer.md"),
    "You are the solutions-engineer.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "universal", "1-engineering-principles.md"),
    "- Ship small and fast.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "architecture", "2-architecture-principles.md"),
    "- Keep boundaries clean.\n",
  );
  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "coding-rules", "universal", "coding-rules.md"),
    "- Keep modules focused.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "solutions-engineer",
    "--tool",
    "codex",
    "--languages",
    "typescript",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(agents, /You are the solutions-engineer\./u);
  assert.equal(agents.includes("includes:"), false);
  assert.match(agents, /- Ship small and fast\./u);
  assert.equal(agents.includes("Keep boundaries clean."), true);
  assert.equal(agents.includes("Keep modules focused."), true);
});

test("Build loads the knowledge base when only a framework is selected", async () => {
  const fixture = await createInitFixture();

  await fs.writeFile(
    path.join(fixture.knowledgeBasePath, "general-principles", "universal", "principles.md"),
    "- Ship small and fast.\n",
  );

  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
    "--frameworks",
    "react",
  ]);

  await execFileAsync(process.execPath, [
    cliEntry,
    "build",
    "--project-path",
    fixture.projectPath,
  ]);

  const agents = await fs.readFile(path.join(fixture.projectPath, "AGENTS.md"), "utf8");

  assert.match(agents, /## Engineering Principles/u);
  assert.match(agents, /- Ship small and fast\./u);
});

async function initCodexProject(fixture) {
  await execFileAsync(process.execPath, [
    cliEntry,
    "init",
    "--project-path",
    fixture.projectPath,
    "--kb-path",
    fixture.knowledgeBasePath,
    "--agent-path",
    fixture.agentPath,
    "--agent-persona",
    "software-developer",
    "--tool",
    "codex",
  ]);
}

function manifestPathOf(fixture) {
  return path.join(fixture.projectPath, ".aie-os", "aie-os.json");
}

async function readManifest(fixture) {
  return JSON.parse(await fs.readFile(manifestPathOf(fixture), "utf8"));
}

async function writeManifest(fixture, manifest) {
  await fs.writeFile(manifestPathOf(fixture), `${JSON.stringify(manifest, null, 2)}\n`);
}

async function runningTag() {
  const { version } = JSON.parse(await fs.readFile(path.join(__dirname, "..", "package.json"), "utf8"));
  return `v${version}`;
}

function buildProject(fixture) {
  return execFileAsync(process.execPath, [cliEntry, "build", "--project-path", fixture.projectPath]);
}

test("Build records aieOsVersion in a project that has none and inserts only that line", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  const { aieOsVersion, ...legacyManifest } = await readManifest(fixture);
  await writeManifest(fixture, legacyManifest);
  const legacyText = await fs.readFile(manifestPathOf(fixture), "utf8");
  const tag = await runningTag();

  const { stderr, stdout } = await buildProject(fixture);
  const recordedText = await fs.readFile(manifestPathOf(fixture), "utf8");

  assert.equal(aieOsVersion, tag);
  assert.equal(stderr, "");
  assert.match(stdout, new RegExp(`Recorded AIE OS ${tag.replace(/\./gu, "\\.")} in \\.aie-os[\\\\/]aie-os\\.json \\("aieOsVersion"\\)\\.`, "u"));
  assert.equal(recordedText, legacyText.replace('"version": "0.1",\n', `"version": "0.1",\n  "aieOsVersion": "${tag}",\n`));
});

test("Build leaves the manifest untouched when aieOsVersion matches the running tag", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  const compactText = JSON.stringify(await readManifest(fixture));
  await fs.writeFile(manifestPathOf(fixture), compactText);

  const { stdout } = await buildProject(fixture);

  assert.equal(await fs.readFile(manifestPathOf(fixture), "utf8"), compactText);
  assert.doesNotMatch(stdout, /Recorded AIE OS|Upgraded AIE OS/u);
});

test("Build upgrades aieOsVersion when the running tag is newer", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  await writeManifest(fixture, { ...(await readManifest(fixture)), aieOsVersion: "v0.0.1" });
  const tag = await runningTag();

  const { stdout } = await buildProject(fixture);

  assert.equal((await readManifest(fixture)).aieOsVersion, tag);
  assert.match(stdout, new RegExp(`Upgraded AIE OS in \\.aie-os[\\\\/]aie-os\\.json \\("aieOsVersion"\\) from v0\\.0\\.1 to ${tag.replace(/\./gu, "\\.")}\\.`, "u"));
});

test("Build refuses an older running tag before writing anything", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  await writeManifest(fixture, { ...(await readManifest(fixture)), aieOsVersion: "v999.0.0" });
  const manifestText = await fs.readFile(manifestPathOf(fixture), "utf8");
  const tag = await runningTag();

  await assert.rejects(buildProject(fixture), (error) => {
    assert.equal(error.code, 1);
    assert.equal(
      error.stderr,
      [
        `Refusing to build with AIE OS ${tag}: ${path.join(".aie-os", "aie-os.json")} requires v999.0.0 ("aieOsVersion").`,
        "Rerun the same command with tag v999.0.0.",
        "",
      ].join("\n"),
    );
    return true;
  });

  assert.equal(await fs.readFile(manifestPathOf(fixture), "utf8"), manifestText);
  await assert.rejects(fs.access(path.join(fixture.projectPath, "AGENTS.md")));
  await assert.rejects(fs.access(path.join(fixture.projectPath, ".aie-os", "build")));
});

test("Build refuses an older running tag even when the newer manifest does not validate", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  const { selection, ...manifest } = await readManifest(fixture);
  await writeManifest(fixture, { ...manifest, aieOsVersion: "v999.0.0" });

  await assert.rejects(buildProject(fixture), (error) => {
    assert.match(error.stderr, /^Refusing to build with AIE OS v\d+\.\d+\.\d+: /u);
    assert.doesNotMatch(error.stderr, /Expected selection/u);
    return true;
  });
});

test("Build keeps the previous aieOsVersion when the build fails", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  await writeManifest(fixture, { ...(await readManifest(fixture)), aieOsVersion: "v0.0.1" });
  await fs.writeFile(path.join(fixture.projectPath, "AGENTS.md"), "# Hand written instructions\n");

  await assert.rejects(buildProject(fixture), /Refusing to overwrite AGENTS\.md/u);

  assert.equal((await readManifest(fixture)).aieOsVersion, "v0.0.1");
});

test("Build keeps the previous aieOsVersion when writing artifacts fails", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  await writeManifest(fixture, { ...(await readManifest(fixture)), aieOsVersion: "v0.0.1" });
  await fs.mkdir(path.join(fixture.projectPath, ".aie-os", "build"), { recursive: true });
  await fs.writeFile(path.join(fixture.projectPath, ".aie-os", "build", "installed-artifacts.json"), "{");

  await assert.rejects(buildProject(fixture), /Invalid JSON installed-artifacts file/u);

  await fs.access(path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"));
  assert.equal((await readManifest(fixture)).aieOsVersion, "v0.0.1");
});

test("Build rejects an aieOsVersion that is not a release tag", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);
  await writeManifest(fixture, { ...(await readManifest(fixture)), aieOsVersion: "latest" });

  await assert.rejects(buildProject(fixture), (error) => {
    assert.match(error.stderr, /Expected aieOsVersion to be a release tag like v1\.2\.3 in manifest: /u);
    return true;
  });
});

test("Build never copies aieOsVersion into the effective context", async () => {
  const fixture = await createInitFixture();
  await initCodexProject(fixture);

  await buildProject(fixture);

  const effectiveContext = await fs.readFile(path.join(fixture.projectPath, ".aie-os", "build", "effective-context.json"), "utf8");
  assert.equal(effectiveContext.includes("aieOsVersion"), false);
});
