const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const test = require("node:test");
const { buildFixture, createRichContextFixture } = require("./rich-context-fixture");

const marker = "This file is generated by AIE OS. Do not edit directly.";
const rulesDirectory = path.join(".claude", "rules", "aie");

async function listRuleFiles(fixture) {
  return (await fs.readdir(path.join(fixture.projectPath, rulesDirectory))).sort();
}

async function readProjectFile(fixture, relativePath) {
  return fs.readFile(path.join(fixture.projectPath, relativePath), "utf8");
}

async function exists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function updateManifestSelection(fixture, selection) {
  const manifestPath = path.join(fixture.projectPath, ".aie-os", "aie-os.json");
  const manifest = JSON.parse(await fs.readFile(manifestPath, "utf8"));
  manifest.selection = { ...manifest.selection, ...selection };
  await fs.writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

test("Claude CLAUDE.md holds only the persona, critical rules, and a pointer to the rule files", async () => {
  const fixture = await createRichContextFixture("claude");

  const { stdout } = await buildFixture(fixture);
  const claude = await readProjectFile(fixture, "CLAUDE.md");

  assert.match(claude, /^# CLAUDE\n\nThis file is generated by AIE OS\. Do not edit directly\.\n\n## Persona\n\nYou are a software developer\./u);
  assert.match(claude, /## Critical Rules\n\n### Agent Rules\n\n- Agent critical rule\./u);
  assert.match(claude, /## Additional Rules\n\nFollow every rule file in `\.claude\/rules\/aie\/`\./u);
  assert.deepEqual(claude.match(/^## .+$/gmu), ["## Persona", "## Critical Rules", "## Additional Rules"]);
  assert.deepEqual(claude.match(/^### .+$/gmu), [
    "### Agent Rules",
    "### Coding Rules",
    "### Project Coding Rules",
  ]);
  assert.match(stdout, /Read `CLAUDE\.md` and `\.claude\/rules\/aie\/`/u);
});

test("Claude writes one unscoped rule file per section with the same content Codex renders", async () => {
  const fixture = await createRichContextFixture("claude,codex");

  await buildFixture(fixture);

  assert.deepEqual(await listRuleFiles(fixture), [
    "agent-rules.md",
    "application-type-cli.md",
    "coding-rules.md",
    "engineering-principles.md",
    "framework-react.md",
    "language-typescript.md",
    "project-coding-rules-api.md",
    "project-coding-rules.md",
  ]);

  assert.equal(
    await readProjectFile(fixture, path.join(rulesDirectory, "engineering-principles.md")),
    `${marker}\n\n## Engineering Principles\n\n- Ship small and fast.\n\n### Architecture Principles\n\n- Keep boundaries clean.\n`,
  );
  assert.match(
    await readProjectFile(fixture, path.join(rulesDirectory, "coding-rules.md")),
    /### Cli Typescript\n\n- Conditional CLI TypeScript rule\./u,
  );

  const agents = await readProjectFile(fixture, "AGENTS.md");
  for (const ruleFile of await listRuleFiles(fixture)) {
    const contents = await readProjectFile(fixture, path.join(rulesDirectory, ruleFile));
    assert.equal(contents.startsWith(`${marker}\n\n## `), true);
    assert.equal(agents.includes(contents.slice(`${marker}\n\n`.length).trimEnd()), true);
  }

  const ledger = JSON.parse(await readProjectFile(fixture, ".aie-os/build/installed-artifacts.json"));
  assert.equal(ledger.paths.includes(".claude/rules/aie/coding-rules.md"), true);
});

test("Claude removes rule files whose section disappears and keeps user rule files", async () => {
  const fixture = await createRichContextFixture("claude");
  await buildFixture(fixture);

  const userRule = path.join(fixture.projectPath, ".claude", "rules", "mine.md");
  await fs.writeFile(userRule, "- My own rule.\n");

  await updateManifestSelection(fixture, { languages: [] });
  await buildFixture(fixture);

  const ruleFiles = await listRuleFiles(fixture);
  assert.equal(ruleFiles.includes("language-typescript.md"), false);
  assert.equal(ruleFiles.includes("coding-rules.md"), true);
  assert.equal(await fs.readFile(userRule, "utf8"), "- My own rule.\n");

  await updateManifestSelection(fixture, { tools: ["codex"] });
  await buildFixture(fixture);

  assert.deepEqual(await listRuleFiles(fixture), []);
  assert.equal(await fs.readFile(userRule, "utf8"), "- My own rule.\n");
});

test("Claude refuses to overwrite a rule file it did not generate unless --force-overwrite is passed", async () => {
  const fixture = await createRichContextFixture("claude");
  const userOwnedRule = path.join(fixture.projectPath, rulesDirectory, "coding-rules.md");

  await fs.mkdir(path.dirname(userOwnedRule), { recursive: true });
  await fs.writeFile(userOwnedRule, "- Hand written.\n");

  await assert.rejects(buildFixture(fixture), (error) => {
    assert.match(error.stderr, /Refusing to overwrite \.claude\/rules\/aie\/coding-rules\.md: it was not generated by AIE OS\./u);
    return true;
  });
  assert.equal(await exists(path.join(fixture.projectPath, "CLAUDE.md")), false);
  assert.equal(await fs.readFile(userOwnedRule, "utf8"), "- Hand written.\n");

  await buildFixture(fixture, ["--force-overwrite"]);

  assert.match(await fs.readFile(userOwnedRule, "utf8"), /^This file is generated by AIE OS\./u);
});
