import path from "node:path";
import { generatedFileMarker } from "../agentAdapters";
import { fileExists, readText } from "../context/filesystem";

export type OutputFileGuardInput = {
  forceOverwrite: boolean;
  outputFiles: readonly string[];
  projectPath: string;
};

export async function ensureOutputFilesAreReplaceable(
  input: OutputFileGuardInput,
): Promise<void> {
  if (input.forceOverwrite) {
    return;
  }

  for (const outputFile of input.outputFiles) {
    const outputFilePath = path.join(input.projectPath, outputFile);

    if (!(await fileExists(outputFilePath))) {
      continue;
    }

    if (isGeneratedByAieOs(await readText(outputFilePath))) {
      continue;
    }

    throw new Error(
      [
        `Refusing to overwrite ${outputFile}: it was not generated by AIE OS.`,
        "Pass --force-overwrite to replace it.",
      ].join("\n"),
    );
  }
}

function isGeneratedByAieOs(contents: string): boolean {
  return contents.includes(generatedFileMarker);
}
