import path from "node:path";
import { generatedFileMarker } from "../agentAdapters";
import { fileExists, readText } from "../context/filesystem";

export type OutputFileGuardInput = {
  forceOverwrite: boolean;
  outputFile: string;
  projectPath: string;
};

export async function ensureOutputFileIsReplaceable(
  input: OutputFileGuardInput,
): Promise<void> {
  if (input.forceOverwrite) {
    return;
  }

  const outputFilePath = path.join(input.projectPath, input.outputFile);

  if (!(await fileExists(outputFilePath))) {
    return;
  }

  if (isGeneratedByAieOs(await readText(outputFilePath))) {
    return;
  }

  throw new Error(
    [
      `Refusing to overwrite ${input.outputFile}: it was not generated by AIE OS.`,
      "Pass --force-overwrite to replace it, or choose another name with --output-file.",
    ].join("\n"),
  );
}

function isGeneratedByAieOs(contents: string): boolean {
  return contents.includes(generatedFileMarker);
}
