import path from "node:path";
import { readText } from "../files";
import { codexSkillAdapter } from "./codexSkillAdapter";
import type { Adapter, AdapterOutput } from "./types";

export const codexAdapter: Adapter = {
  async build(input): Promise<AdapterOutput> {
    const skillAdapterOutput = codexSkillAdapter.build(input);
    const warnings = input.effectiveContext.skills.flatMap((skill) => skill.warnings);
    const renderedSections = await Promise.all(
      input.effectiveContext.sections.map(async (section, index) => {
        const filePath = path.isAbsolute(section.file)
          ? section.file
          : path.resolve(input.projectPath, section.file);

        return [
          `## ${index + 1}. ${section.layer}: ${section.heading}`,
          "",
          (await readText(filePath)).trim(),
        ].join("\n");
      }),
    );

    const contents = [
      "# AGENTS",
      "",
      "This file is generated by AIE OS. Do not edit directly.",
      "",
      skillAdapterOutput.markdown,
      renderedSections.join("\n\n"),
      "",
    ].join("\n");

    return {
      files: [
        {
          contents,
          path: "AGENTS.md",
        },
      ],
      primaryArtifact: "AGENTS.md",
      skillAdapterOutput,
      warnings,
    };
  },
  tool: "codex",
};
