import path from "node:path";
import { commandName } from "./commandName";
import type { ExecutionOptions, InitExecutionOptions, ParsedOptions } from "./types";

const DEFAULT_OUTPUT_FILE = "AGENTS.md";
const FLAG_OPTIONS = new Set(["--force-overwrite"]);
const BUILD_OPTIONS = ["--project-path", "--output-file", "--force-overwrite"];
const INIT_OPTIONS = [
  "--project-path",
  "--kb-path",
  "--agent-path",
  "--skills-path",
  "--agent-persona",
  "--languages",
  "--application-type",
  "--frameworks",
];
const REMOVED_OPTIONS: Record<string, string> = {
  "--target-agent": [
    "--target-agent has been removed. Use --output-file <name> instead.",
    `For example: ${commandName} build --output-file CLAUDE.md`,
  ].join("\n"),
};
const INIT_DEFAULTS = {
  agentPath: "aie-os/content/agent",
  kbPath: "aie-os/content/knowledge-base",
  skillsPath: "aie-os/content/skills",
} as const;

export const usageText = `AIE OS

Usage:
  ${commandName} init [options]
  ${commandName} build [options]

Commands:
  init
    Initialize AIE OS for the target project. With no init config arguments, init prompts interactively. If any init config argument is provided, init becomes explicit and requires all mandatory init options.
  build
    Build the effective context and generate tool-specific artifacts. Build is non-interactive.

Notes:
  - init prompts only when no init configuration arguments are provided.
  - Passing any init configuration argument switches init to explicit mode.
  - In explicit mode, omitted optional values are treated as empty and required values must be provided.
  - build never prompts and fails explicitly when required values are missing.

Init options:
  --project-path                    Target repository. Defaults to the current directory.
  --kb-path                         Knowledge-base path.
  --agent-path                      Agent path.
  --skills-path                     (optional) Skills path.
  --agent-persona                   Persona. Accepted values are markdown file names from [agent-path]/persona without .md.
  --languages                       (optional) Comma-separated language folder names from [kb-path]/coding-rules/language.
  --application-type                (optional) Comma-separated application-type folder names from [kb-path]/coding-rules/application-type.
  --frameworks                      (optional) Comma-separated framework folder names from [kb-path]/coding-rules/framework.

Build options:
  --project-path                    Target repository. Defaults to the current directory.
  --output-file                     (optional) Name of the generated instructions file. Defaults to AGENTS.md. Must be a file name, not a path.
  --force-overwrite                 (optional) Replace the output file even when it was not generated by AIE OS.

Other options:
  -h, --help                        Show help.

Examples:
  ${commandName} init
  ${commandName} init --project-path /repo
  ${commandName} init --kb-path content/knowledge-base --agent-path content/agent --agent-persona software-developer
  ${commandName} init --kb-path content/knowledge-base --agent-path content/agent --agent-persona software-developer --languages typescript --application-type cli
  ${commandName} build
  ${commandName} build --output-file CLAUDE.md
  ${commandName} build --output-file CLAUDE.md --force-overwrite`;

export function parseCommandInput(argv: string[]): ParsedOptions {
  const [command, ...rest] = argv;

  if (!command) {
    return {
      command: null,
      help: false,
      options: {},
    };
  }

  if (command === "-h" || command === "--help") {
    return {
      command: null,
      help: true,
      options: {},
    };
  }

  if (command.startsWith("--")) {
    return {
      command: null,
      help: false,
      options: {},
    };
  }

  if (command !== "init" && command !== "build") {
    throw new Error(`Unknown command: ${command}`);
  }

  const parsed: ParsedOptions = {
    command,
    help: false,
    options: {},
  };

  for (let index = 0; index < rest.length; index += 1) {
    const argument = rest[index];

    if (argument === "-h" || argument === "--help") {
      parsed.help = true;
      continue;
    }

    if (!argument.startsWith("--")) {
      throw new Error(`Unexpected argument: ${argument}`);
    }

    if (FLAG_OPTIONS.has(argument)) {
      parsed.options[argument] = "true";
      continue;
    }

    const value = rest[index + 1];
    if (value === undefined || value.startsWith("--")) {
      throw new Error(`Missing value for option ${argument}`);
    }

    parsed.options[argument] = value;
    index += 1;
  }

  return parsed;
}

export function resolveExecutionOptions(
  parsed: ParsedOptions,
  cwd: string,
): ExecutionOptions {
  if (!parsed.command) {
    throw new Error("You must specify a command.");
  }

  const projectPath = resolveProjectPath(cwd, parsed.options["--project-path"]);

  if (parsed.help) {
    return parsed.command === "init"
      ? {
          command: "init",
          defaults: { ...INIT_DEFAULTS },
          initialSelections: {},
          mode: "interactive",
          providedPaths: {},
          projectPath,
        }
      : {
          command: "build",
          forceOverwrite: false,
          outputFile: DEFAULT_OUTPUT_FILE,
          projectPath,
        };
  }

  if (parsed.command === "build") {
    rejectUnsupportedOptions(parsed.options, BUILD_OPTIONS, "build");

    return {
      command: "build",
      forceOverwrite: parsed.options["--force-overwrite"] === "true",
      outputFile: resolveOutputFile(parsed.options["--output-file"]),
      projectPath,
    };
  }

  rejectUnsupportedOptions(parsed.options, INIT_OPTIONS, "init");

  const defaults = { ...INIT_DEFAULTS };
  const mode = hasExplicitInitConfig(parsed.options) ? "explicit" : "interactive";

  const initOptions: InitExecutionOptions = {
    command: "init",
    defaults,
    initialSelections: {
      applicationTypes: parseCsvSelections(parsed.options["--application-type"]),
      frameworks: parseCsvSelections(parsed.options["--frameworks"]),
      languages: parseCsvSelections(parsed.options["--languages"]),
      persona: normalizeOptionalSelection(parsed.options["--agent-persona"]),
    },
    mode,
    providedPaths: {
      agentPath: normalizeCliPathOption(cwd, projectPath, parsed.options["--agent-path"]),
      kbPath: normalizeCliPathOption(cwd, projectPath, parsed.options["--kb-path"]),
      skillsPath: normalizeCliPathOption(cwd, projectPath, parsed.options["--skills-path"]),
    },
    projectPath,
  };

  return initOptions;
}

function hasExplicitInitConfig(options: Record<string, string>): boolean {
  return INIT_OPTIONS.filter((optionName) => optionName !== "--project-path").some((optionName) =>
    Object.prototype.hasOwnProperty.call(options, optionName),
  );
}

function resolveOutputFile(configuredOutputFile: string | undefined): string {
  if (configuredOutputFile === undefined) {
    return DEFAULT_OUTPUT_FILE;
  }

  const outputFile = configuredOutputFile.trim();

  if (outputFile === "") {
    throw new Error("Invalid --output-file: expected a file name.");
  }

  if (outputFile !== path.basename(outputFile) || outputFile === "." || outputFile === "..") {
    throw new Error(`Invalid --output-file "${outputFile}": expected a file name, not a path.`);
  }

  return outputFile;
}

function resolveProjectPath(cwd: string, explicitPath?: string): string {
  if (!explicitPath) {
    return cwd;
  }

  return path.resolve(cwd, explicitPath);
}

function rejectUnsupportedOptions(
  options: Record<string, string>,
  allowedOptions: string[],
  commandLabel: string,
): void {
  const unsupported = Object.keys(options).filter((option) => !allowedOptions.includes(option));

  if (unsupported.length === 0) {
    return;
  }

  const removedGuidance = unsupported
    .map((option) => REMOVED_OPTIONS[option])
    .filter((guidance) => guidance !== undefined);

  if (removedGuidance.length > 0) {
    throw new Error(removedGuidance.join("\n"));
  }

  throw new Error(
    [
      `Unsupported option(s) for ${commandLabel}: ${unsupported.join(", ")}`,
      `Supported options: ${allowedOptions.join(", ")}`,
    ].join("\n"),
  );
}

function parseCsvSelections(value: string | undefined): string[] | undefined {
  if (!value) {
    return undefined;
  }

  const selections = value
    .split(",")
    .map((entry) => entry.trim())
    .filter((entry) => entry !== "");

  return selections.length === 0 ? undefined : selections;
}

function normalizeOptionalSelection(value: string | undefined): string | undefined {
  if (!value) {
    return undefined;
  }

  const normalized = value.trim();
  return normalized === "" ? undefined : normalized;
}

function normalizeCliPathOption(
  cwd: string,
  projectPath: string,
  configuredPath: string | undefined,
): string | undefined {
  if (configuredPath === undefined) {
    return undefined;
  }

  if (configuredPath.trim() === "") {
    return "";
  }

  const absolutePath = path.isAbsolute(configuredPath)
    ? configuredPath
    : path.resolve(cwd, configuredPath);

  return toProjectRelative(projectPath, absolutePath);
}

function toProjectRelative(projectPath: string, absolutePath: string): string {
  const relativePath = path.relative(projectPath, absolutePath);

  if (relativePath === "") {
    return ".";
  }

  if (!relativePath.startsWith("..")) {
    return relativePath;
  }

  return absolutePath;
}
